# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Optimierungsverfahren, Modellierung und Simulation (DSCB410)
author: Dennis Janka
logo: HKA_IWI_Bildmarke-h_RGB.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
#repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: true
#  use_repository_button: true

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    mathjax_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "R": "\\mathbb{R}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat" : ["\\left[\\begin{array}{}"] #am Ende noch {} sonst wir der erste Eintrag der Matrix verschluckt
          "emat" : ["\\end{array}\\right]"]
          "scikit": ["\\texttt{scikit-learn}"]
          "derv": ["\\frac{\\partial #1}{\\partial #2}", 2]
          "dervquad": ["\\frac{\\partial^2 #1}{\\partial #2^2}", 2]
          "dervzwei": ["\\frac{\\partial^2 #1}{\\partial {#2} \\partial {#3}}", 3]
          "mat": ["\\mathbf{#1}", 1]
          "v": ["\\mathbf{#1]", 1]

parse:   
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist